MVCCRUD/Models/Aprendix.cs
using System;
using System.Collections.Generic;

namespace MVCCRUD.Models;

public partial class Aprendix
{
    public int IDaprendiz { get; set; }

    public string NombreAprendiz { get; set; } = null!;

    public string ApellidoAprendiz { get; set; } = null!;
}

MVCCRUD/Models/ErrorViewModel.cs
namespace MVCCRUD.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCCRUD/Models/MvccrudContext.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MVCCRUD.Models;

public partial class MvccrudContext : DbContext
{
    public MvccrudContext()
    {
    }

    public MvccrudContext(DbContextOptions<MvccrudContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Aprendix> Aprendices { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) { }
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
//        => optionsBuilder.UseSqlServer("server=localhost; database=MVCCRUD; integrated security=true; TrustServerCertificate=Yes");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Aprendix>(entity =>
        {
            entity.HasKey(e => e.IDaprendiz).HasName("PK__APRENDIC__56564FF850A116CB");

            entity.ToTable("APRENDICES");

            entity.Property(e => e.IDaprendiz).HasColumnName("iDaprendiz");
            entity.Property(e => e.ApellidoAprendiz)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("apellidoAprendiz");
            entity.Property(e => e.NombreAprendiz)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("nombreAprendiz");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

MVCCRUD/Controllers/AprendicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCCRUD.Models;

namespace MVCCRUD.Controllers
{
    public class AprendicesController : Controller
    {
        private readonly MvccrudContext _context;

        public AprendicesController(MvccrudContext context)
        {
            _context = context;
        }

        // GET: Aprendices
        public async Task<IActionResult> Index()
        {
            return View(await _context.Aprendices.ToListAsync());
        }

        // GET: Aprendices/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aprendix = await _context.Aprendices
                .FirstOrDefaultAsync(m => m.IDaprendiz == id);
            if (aprendix == null)
            {
                return NotFound();
            }

            return View(aprendix);
        }

        // GET: Aprendices/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Aprendices/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IDaprendiz,NombreAprendiz,ApellidoAprendiz")] Aprendix aprendix)
        {
            if (ModelState.IsValid)
            {
                _context.Add(aprendix);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(aprendix);
        }

        // GET: Aprendices/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aprendix = await _context.Aprendices.FindAsync(id);
            if (aprendix == null)
            {
                return NotFound();
            }
            return View(aprendix);
        }

        // POST: Aprendices/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IDaprendiz,NombreAprendiz,ApellidoAprendiz")] Aprendix aprendix)
        {
            if (id != aprendix.IDaprendiz)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(aprendix);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AprendixExists(aprendix.IDaprendiz))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(aprendix);
        }

        // GET: Aprendices/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aprendix = await _context.Aprendices
                .FirstOrDefaultAsync(m => m.IDaprendiz == id);
            if (aprendix == null)
            {
                return NotFound();
            }

            return View(aprendix);
        }

        // POST: Aprendices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var aprendix = await _context.Aprendices.FindAsync(id);
            if (aprendix != null)
            {
                _context.Aprendices.Remove(aprendix);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AprendixExists(int id)
        {
            return _context.Aprendices.Any(e => e.IDaprendiz == id);
        }
    }
}

MVCCRUD/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVCCRUD.Models;
using System.Diagnostics;

namespace MVCCRUD.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVCCRUD/Views/Aprendices/Create.cshtml
@model MVCCRUD.Models.Aprendix

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Aprendiz</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NombreAprendiz" class="control-label"></label>
                <input asp-for="NombreAprendiz" class="form-control" />
                <span asp-validation-for="NombreAprendiz" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApellidoAprendiz" class="control-label"></label>
                <input asp-for="ApellidoAprendiz" class="form-control" />
                <span asp-validation-for="ApellidoAprendiz" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCCRUD/Views/Aprendices/Delete.cshtml
@model MVCCRUD.Models.Aprendix

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Aprendix</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreAprendiz)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreAprendiz)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApellidoAprendiz)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApellidoAprendiz)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IDaprendiz" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MVCCRUD/Views/Aprendices/Details.cshtml
@model MVCCRUD.Models.Aprendix

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Aprendix</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreAprendiz)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreAprendiz)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApellidoAprendiz)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApellidoAprendiz)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.IDaprendiz">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MVCCRUD/Views/Aprendices/Edit.cshtml
@model MVCCRUD.Models.Aprendix

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Aprendix</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IDaprendiz" />
            <div class="form-group">
                <label asp-for="NombreAprendiz" class="control-label"></label>
                <input asp-for="NombreAprendiz" class="form-control" />
                <span asp-validation-for="NombreAprendiz" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApellidoAprendiz" class="control-label"></label>
                <input asp-for="ApellidoAprendiz" class="form-control" />
                <span asp-validation-for="ApellidoAprendiz" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCCRUD/Views/Aprendices/Index.cshtml
@model IEnumerable<MVCCRUD.Models.Aprendix>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NombreAprendiz)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApellidoAprendiz)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NombreAprendiz)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ApellidoAprendiz)
            </td>
            <td>
                <a asp-action="Edit" class="btn btn-warning" asp-route-id="@item.IDaprendiz">Edit</a> |
                    <a asp-action="Details" class="btn btn-primary" asp-route-id="@item.IDaprendiz">Details</a> |
                    <a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.IDaprendiz">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

MVCCRUD/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bienvenido</h1>
    <p>
        para ver los Aprendices guardados dirijase a aprendices o pulse el
        siguiente boton.
    </p>
    <a class="btn btn-primary" href="@Url.Action("Index", "Aprendices")">Aprendices</a>
</div>

MVCCRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCCRUD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCCRUD.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCCRUD</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Aprendices" asp-action="Index">Aprendices</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MVCCRUD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>